# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Debian-7.4-i386"
  config.vm.hostname = "debian-box"

  config.vm.network "forwarded_port", guest: 80, host: 8500, host_ip: "127.0.0.1", auto_correct: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    vb.gui = false
  
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file Debian-7.4-i386.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # group { "puppet":
  #   ensure => "present",
  # }
  #
  # File { owner => 0, group => 0, mode => 0644 }
  #
  # file { '/etc/motd':
  #
  # content => "Welcome to your Vagrant-built virtual machine!
  #               Managed by Puppet.\n"
  # }
  
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
    puppet.options = ["--templatedir", "/vagrant/templates"]
  end
end
